### ISSUE TITLE
Error on `cordova plugin add cordova-pdf-generator`

### ISSUE THREAD

**Issue by jfoclpf** [cesarvr/pdf-generator#132]
Just to let yo know that your plugin is throwing an error on `cordova platform add android`

```
$ cordova platform add android
Using cordova-fetch for cordova-android@^9.0.0
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms/android
        Package: com.form.parking.violation
        Name: Den_ncia_Estacionamento
        Activity: MainActivity
        Android target: android-29
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@9.0.0
Installing "cordova-pdf-generator" for android
Error during processing of action! Attempting to revert...
Failed to install 'cordova-pdf-generator': CordovaError: Uh oh!
"/home/joao_pimentel_ferreira/form-for-parking-violation/plugins/cordova-pdf-generator/src/android/PDFGenerator.java" not found!
    at copyFile (/home/joao_pimentel_ferreira/form-for-parking-violation/platforms/android/cordova/lib/pluginHandlers.js:207:36)
    at copyNewFile (/home/joao_pimentel_ferreira/form-for-parking-violation/platforms/android/cordova/lib/pluginHandlers.js:232:5)
    at install (/home/joao_pimentel_ferreira/form-for-parking-violation/platforms/android/cordova/lib/pluginHandlers.js:33:17)
    at ActionStack.process (/home/joao_pimentel_ferreira/form-for-parking-violation/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/home/joao_pimentel_ferreira/form-for-parking-violation/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:112:24)
    at PluginManager.addPlugin (/home/joao_pimentel_ferreira/form-for-parking-violation/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:142:21)
    at /home/joao_pimentel_ferreira/form-for-parking-violation/platforms/android/cordova/Api.js:159:78
Uh oh!
"/home/joao_pimentel_ferreira/form-for-parking-violation/plugins/cordova-pdf-generator/src/android/PDFGenerator.java" not found!
```

The same happens also on `cordova plugin add cordova-pdf-generator`

Apparently it has to do with this file: **`plugins/cordova-pdf-generator/src/android/PDFGenerator.java`** which is "not found"

**Comment by jfoclpf** [comment]
my mistake
